# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ReactNativeStarter' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'ReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'ReactNativeStarter-tvOS' do
  target 'ReactNativeStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
